In [59]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import datetime as dt
import glob
import SNobject as sn
import probe_info
from functions import convert_wind,parse_currtime,calc_dewpoint,plot_meteogram,get_winddir_string,C_to_F,calc_mslp

# Hard Coded Stesonet locations (year can change)
probe_locs = probe_info.probe_locs_2017

# rows for StickNet data units for Vars are C, %, hPa, m/s, m/s, and degrees
col_names = ['probe', 'Lat', 'Lon', 'YYMMDD', 'HHMM','T', 'RH', 'P', 'WS','WSMAX', 'WD', 'BATT']

class SNFile(object):
    def __init__(self, filename):
        """ initialize a SN object based on a filename given """
        self.year = int(filename[-17:-13])
        self.month = int(filename[-13:-11])
        self.day = int(filename[-11:-9])
        self.hour = int(filename[-8:-6])
        self.minute = int(filename[-6:-4])
        self.datetime = dt.datetime(self.year,self.month,self.day,self.hour,self.minute)
        self.filename = filename
        self.probe = filename[-23:-18]

    def read_realtime(self):
        """ read the one line of the RT sticknet text file and split apart.
       """
        f = open(self.filename)
        line = f.readline().split(',')
        return line

#     def read_daq(self,identifier='stesonet'):
#         """ read the DAQ box output text file and parse into columns. Identify with 
#         call input whether the filetype is from StesoNet probe or finescale, as this determines 
#         number of columns to read """
#         if identifier == 'stesonet':
#             sn = pd.read_csv(self.filename, names=['time','T','RH','P','windsp','winddir','batt'], 
#                 dtype={'time':np.str},header=1,parse_dates=[0],date_parser=self.parse,error_bad_lines=False)
#         elif identifier == 'finescale':
#         # for rapid probes, that don't have the extra data point at the end of the line (i.e. battery voltage)
#             sn = pd.read_csv(self.filename, names=['time','T','RH','P','windsp','winddir'],
#                          dtype={'time':np.str},header=1,parse_dates=[0],date_parser=self.parse,error_bad_lines=False)
         
#         sn['ID'] = pd.Series(self.probe,index=sn.index)
#         sn.index = sn['time']
#         return sn

#     def read_daq_qced(self,identifier):
#         """ read the QC'd DAQ box output text file and parse into columns. Identify with 
#         call input whether the filetype is from StesoNet probe or finescale, as this determines 
#         number of columns to read """        
#         if identifier == 'stesonet':
#             sn = pd.read_csv(self.filename, names=['time','T','RH','P','windsp','winddir','batt','tflag','wflag'], 
#                 dtype={'time':np.str},header=1,parse_dates=[0],date_parser=self.parse,error_bad_lines=False)
#         elif identifier == 'finescale':
#         # for rapid probes, that don't have the extra data point at the end of the line (i.e. battery voltage)
#             sn = pd.read_csv(self.filename, names=['time','T','RH','P','windsp','winddir','tflag','wflag'],
#                          dtype={'time':np.str},header=1,parse_dates=[0],date_parser=self.parse,error_bad_lines=False)
         
#         sn['ID'] = pd.Series(self.probe,index=sn.index)
#         sn.index = sn['time']
#         return sn

def get_files(filedir, probe_id, starttime, endtime):
    ''' this seems like a janky way to do it, but is actually 3x faster than
        making a loop of files.'''

    day_str = np.array([(starttime+dt.timedelta(days=i)).strftime("%Y%m%d") 
                     for i in range((endtime-starttime).days+1)])


    # find all SN files with days between starttime and endtime
    files = [glob.glob(filedir+probe_id+'_'+string+'_*.txt') for string in day_str]
    files = [f for subf in files for f in subf] # flatten list in case of multiple days
    
    if files:
         # sort files by date, then find nearest indices for all the dates, and loop over that
        sorted_files = sorted(files,key=lambda f: dt.datetime.strptime(f[-17:-4],'%Y%m%d_%H%M'))
        fdates = [dt.datetime.strptime(f[-17:-4],'%Y%m%d_%H%M') for f in sorted_files] 
        _, idx1 = min((abs(val-starttime), idx) for (idx, val) in enumerate(fdates))
        _, idx2 = min((abs(val-endtime),   idx) for (idx, val) in enumerate(fdates))
        files= sorted_files[idx1:idx2+1]
        
    return files


def format_ID(n):
    if n > 12:
        probe_id = "02{0}A".format("%02d"%n)
    else:
        probe_id = "01{0}A".format("%02d"%n)
        
    return probe_id
    
def write_to_html(html,filedir, probe_id, endtime, d):
    ''' all inputs are created in other function
    Writes to html file for website Observation Table.
    Writes out City name, 4-letter city identifer, probe id, current T, Td,
    RH, WS, WD (string format), wind gust, 24 hr max T, 24 hour min T, 24 hour Max wind gust,
    index of max wind gust (idk why this is needed), batter, MSLP.
    Units for temps are F, wind is kt, pressure is hPa, and battery is Volts. '''
    
    # 24 hour data 
    s = endtime - dt.timedelta(hours=24)
    files = get_files(filedir, probe_id, s, endtime)

    data, dates = [],[] # to put data in for faster looping
    for f in files:
        sn_data = SNFile(f)
        data.append(sn_data.read_realtime())
        dates.append(sn_data.datetime)

    met24 = pd.DataFrame(data, index=dates, columns=col_names)
    met24 = met24[s:endtime] # just in case 
    met24.drop(columns=['probe'], inplace=True)
    met24 = met24.astype(float)


    Tmax = np.round(C_to_F(np.amax(met24['T'].values)),1)     # F
    Tmin = np.round(C_to_F(np.amin(met24['T'].values)),1)      # F # kts
    WSgustmax = np.round(np.amax(met24['WSMAX'].values)* 1.94384, 1)
    wsindx = np.argmax(met24['WSMAX'].values) # not sure why I need this...

    # current vals
    T = C_to_F(d['T']).values[0]
    Td = C_to_F(calc_dewpoint(d['T'].values, d['RH'].values))[0]
    RH = d['RH'].values[0]
    WS = np.round(d['WS']* 1.94384, 1).values[0]
    WSgust = np.round(d['WSMAX']* 1.94384, 1).values[0]
    WD = get_winddir_string(d['WD'].values)
    batt = d['BATT'].values[0]
    MSLP = np.round(calc_mslp(d['T'].values,d['P'].values,d['Elevation'].values),1)[0]
    city = probe_locs[probe_id][4]
    id_name = probe_locs[probe_id][3]
    time = sn_data.datetime

    text1 = f'{city},{id_name},{probe_id},{time},{T},{Td},{RH},{WS},{WD},{WSgust:4.1f},'
    text2 = f'{Tmax},{Tmin},{WSgustmax:4.1f},{wsindx},{batt},{MSLP}'
    text = text1+text2

    print(text)
    #html.write(text)

    
def get_sticknet_data(filedir,starttime,endtime, probes=[],dataset="subset",
                      plotmeteograms=False, returndata=False, html=None):
    
    '''
    This is a somewhat complicated function that performs multiple tasks depending on the inputs.
    It is designed to be helpful for the website, but should also be used for post processing and analysis. 
    
    INPUTS:
    
    filedir   - location of the data in real time form (each file only contains 1 min of data for 1 SN)
    starttime - datetime object of start time of data you want. Only valid when dataset="subset"
    endtime   - datetime object of end time of data you want. 
    probes    - number associated with the SNs you want (1 = "0101A", 24 = "0224A"). Must be in list 
                format
                
    dataset   - can be "subset" or "latest"
    
        if "subset":  Get a range of data. If starttime = endtime, only one minute of data is returned.
                      Used for plotting meteograms, or analysis on a single SN
    
          plotmeteograms - default False. Set to True if you want meteograms to be plotted in the data 
                           range you selected.
          returndata     - default False. set to True if you want the pandas dataframe of the data 
                           returned. If multiple probes are chosen in the "probes" var, only the 
                           first is returned.Latitude, longitude, and elevation are set as attributes
                           for the dataframe.(i.e, df.latitude will give you the latitude)
                           
        if "latest":   Get the a single line of data closest to "endtime". If starttime != endtime, 
                       functionality is the same, but it will be slower.
                       Used for making station plots, oban plots, and for creating files useful for 
                       the website
        
          html           - default None. Set html = an opened text file, and it will write out the
                           data needed for the Obs Table on the website to that file.
                           
    OUTPUTS:
        Returns a Pandas dataframe that will be full ("latest" OR ("subset"&returndata)) 
        or empty ("subset").
        
        All returned dataframes will include the attribute "units", which outputs a reminder
        of the units of each variable.
        
        "latest" returns a dataframe with probe_id as index, with dates as a column.
        "subset" & returndata=True returns a dataframe with dates as the index. Probe ID is 
                 contained in the dataframe attrs
    
    '''

    # create empty dataframe
    met = pd.DataFrame(columns=col_names)

    # loop over all probes
    for i in probes:

        probe_id = format_ID(i)
        print(probe_id)

        files = get_files(filedir, probe_id, starttime, endtime)

        if files: # not empty 

            ### get a subset of data
            if dataset == 'subset':

                    data, dates = [],[] # to put data in for faster looping

                    for f in files: # append data to lists, LOTS faster than appending with pandas
                        sn_data = SNFile(f)
                        data.append(sn_data.read_realtime())
                        dates.append(sn_data.datetime) 

                    met = pd.DataFrame(data, index=dates, columns=col_names)

                    # in case the "nearest time" is really not that near, use Pandas to make sure
                    # times are within what you requested. Clean up dataframe
                    met.drop(columns=['Lat', 'Lon', 'YYMMDD', 'HHMM','probe'], inplace = True)
                    met.sort_index(ascending=True, inplace=True)
                    met = met[starttime:endtime]
                    met = met.astype(float)

                    # set metadata 
#                     met.probe     = probe_id
#                     met.latitude  = probe_locs[probe_id][0]
#                     met.longtidue = probe_locs[probe_id][1]
#                     met.elevation = int(probe_locs[probe_id][2])
#                     met.units = 'T(C), RH(%), P(hPa), WS(m/s), WSMAX(m/s), WD(deg)'
                    
                    met.attrs = {'probe':probe_id, 'latitude':probe_locs[probe_id][0],
                                'longitude':probe_locs[probe_id][1], 'elevation':int(probe_locs[probe_id][2]),
                                'units':'T(C), RH(%), P(hPa), WS(m/s), WSMAX(m/s), WD(deg)'}


                    if plotmeteograms:
                        plot_meteogram(met, probe_id) 

                    if returndata:
                        return met.replace(-999.9,np.nan)

                    met = pd.DataFrame(columns=col_names) # start over for next SN

            ### get the time closest to end time
            ### will find the most recent file available IF endtime is utc.now()
            
            if dataset == 'latest': # get file closest to endtime

                    if len(files) > 1:
                        files = [files[-1]] # need the extra brackets to the next line works

                    print(files)
                    sn_data = SNFile(files[0])
                    d = sn_data.read_realtime()
                    
                    # have date be a column, and probe_id be an index
                    d.insert(0, sn_data.datetime)
                    d = pd.DataFrame([d], index=[sn_data.probe], columns=['date']+col_names).replace(-999.9,np.nan)
                    d.drop(columns=['probe'], inplace=True)
                    d[col_names[1:]] = d[col_names[1:]].apply(pd.to_numeric) 
                    # add more info
                    d['Elevation'] = int(probe_locs[probe_id][2])
                    d['Lat']       = probe_locs[probe_id][0] # overwrite with potentially 
                    d['Lon']       = probe_locs[probe_id][1] # more accurate location from probe_info


                    # data is less than 5 minutes old
                    if abs(sn_data.datetime - endtime) < dt.timedelta(minutes=5):
                        met = met.append(d)  # only have to append a few times, so it's okay to use pandas
                        # Write out info for Obs Table on website
                        if html:
                            write_to_html(html,filedir, probe_id, endtime, d) 

                    else: # no data
                        continue


    # return dataframe. Will be empty if subset % returndata=False
    if (dataset == 'latest'):
        met.drop(columns=['YYMMDD', 'HHMM', 'probe'], inplace=True)
        met.units = 'T(C), RH(%), P(hPa), WS(m/s), WSMAX(m/s), WD(deg)'
        # change to floats
        #print(met)
        to_nums = col_names[5:]+['Lat','Lon','Elevation']
        #met[to_nums] = met[to_nums].apply(pd.to_numeric) 
        met.sort_index(ascending=True, inplace=True)
        return met.replace(-999.9,np.nan)

In [72]:
d.attrs = {'elevation':100}

In [73]:
d.attrs['elevation']

100

In [91]:
d[] = d[col_names[5:]+['Lat','Lon','Elevation']].apply(pd.to_numeric)

In [66]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import datetime as dt
import glob
#from SNmods import get_sticknet_data
import probe_info
from functions import convert_wind,parse_currtime,calc_dewpoint,plot_meteogram,get_winddir_string,C_to_F,calc_mslp

from SNmods_OLD import search_dir

In [69]:
#%%time
date = '20170430'
endtime = dt.datetime(2017,4,30,19,8)
starttime= endtime - dt.timedelta(hours=2)

filedir = r'/Users/jessmcd/Documents/MyPassport_backup/VSE_Data/{}/{}/'.format(date[0:4], date)
probes= [15]#np.arange(1,17,1)

d=get_sticknet_data(filedir, starttime, endtime, probes=probes,dataset='subset',
                    plotmeteograms=False, returndata=True, html=True)
d

0215A

                        T    RH      P   WS  WSMAX     WD  BATT
2017-04-30 17:08:00  24.6  67.6  984.4  2.1    4.7  155.9  10.7
2017-04-30 17:09:00  24.6  68.1  984.4  1.2    3.1  198.1  10.7
2017-04-30 17:10:00  24.5  68.8  984.4  1.5    2.8   46.5  10.7
2017-04-30 17:11:00  24.5  69.0  984.3  1.4    3.3  156.7  10.7
2017-04-30 17:12:00  24.4  68.9  984.3  1.4    4.1  168.9  10.7
...                   ...   ...    ...  ...    ...    ...   ...
2017-04-30 19:04:00  18.7  90.5  983.4  NaN    NaN  165.3  10.7
2017-04-30 19:05:00  18.7  90.6  983.5  NaN    NaN   10.0  10.7
2017-04-30 19:06:00  18.7  90.8  983.6  NaN    NaN  345.0  10.7
2017-04-30 19:07:00  18.7  90.5  983.6  NaN    NaN   85.8  10.7
2017-04-30 19:08:00  18.7  90.4  983.7  NaN    NaN  188.8  10.7

[121 rows x 7 columns]

In [57]:
%%time
date = '20170430'
endtime = dt.datetime(2017,4,30,19,8)
starttime= endtime# - dt.timedelta(hours=23)

filedir = r'/Users/jessmcd/Documents/MyPassport_backup/VSE_Data/{}/{}/'.format(date[0:4], date)
probes= [15]#np.arange(1,17,1)

search_dir(filedir, starttime, endtime, probes=probes,dataset='latest')

0215A
CPU times: user 52.7 ms, sys: 28 ms, total: 80.7 ms
Wall time: 79.8 ms

                dates      P     T  probe   WS     WD    RH
0 2017-04-30 19:08:00  983.7  18.7  0215A  0.0  188.8  90.4

In [58]:
np.nan_to_num(np.nan)

0.0

In [65]:
d.index[-1]

AttributeError: 'NoneType' object has no attribute 'index'

In [126]:
%%timeit
files = []
for dateobj in np.arange(starttime, endtime + dt.timedelta(minutes=1), dt.timedelta(minutes=1)):
    dateobj = pd.to_datetime(dateobj)
    files.extend(glob.glob('{}{}_{}.txt'.format(filedir,probe_id, dateobj.strftime('%Y%m%d_%H%M'))))

129 ms ± 452 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [128]:
%%timeit

def get_files(file_dir, probe_id, starttime, endtime):

    day_str = np.array([(starttime+dt.timedelta(days=i)).strftime("%Y%m%d") 
                     for i in range((endtime-starttime).days+1)])


    # find all SN files with days between starttime and endtime
    files = [glob.glob(filedir+probe_id+'_'+string+'_*.txt') for string in day_str]
    files = [f for subf in files for f in subf] # flatten list in case of multiple days



     # sort files by date, then find nearest indices for all the dates, and loop over that
    sorted_files = sorted(files,key=lambda f: dt.datetime.strptime(f[-17:-4],'%Y%m%d_%H%M'))
    fdates = [dt.datetime.strptime(f[-17:-4],'%Y%m%d_%H%M') for f in sorted_files] 
    _, idx1 = min((abs(val-starttime), idx) for (idx, val) in enumerate(fdates))
    _, idx2 = min((abs(val-endtime),   idx) for (idx, val) in enumerate(fdates))
    return sorted_files[idx1:idx2+1]

52.1 ns ± 0.387 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

In [18]:
%%time
i=2
dataset='latest'
col_names = ['probe', 'Lat', 'Lon', 'YYMMDD', 'HHMM','T', 'RH', 'P', 'WS','WSMAX', 'WD', 'BATT']
html = True
probes = [2]

# string of days requested in subset, helps cut down on processing time 
day_str = np.array([(starttime+dt.timedelta(days=i)).strftime("%Y%m%d") 
                 for i in range((endtime-starttime).days+1)])

# create empty dataframe
met = pd.DataFrame()




# loop over all probes
for i in probes:

    probe_id = format_ID(i)
    print(probe_id)

    # find all SN files with days between starttime and endtime
    files = [glob.glob(filedir+probe_id+'_'+string+'_*.txt') for string in day_str]
    files = [f for subf in files for f in subf] # flatten list in case of multiple days
    
    data, dates = [],[]


    if files: # not empty 

         # sort files by date, then find nearest indices for all the dates, and loop over that
        sorted_files = sorted(files,key=lambda f: dt.datetime.strptime(f[-17:-4],'%Y%m%d_%H%M'))
        fdates = [dt.datetime.strptime(f[-17:-4],'%Y%m%d_%H%M') for f in sorted_files] 
        _, idx1 = min((abs(val-starttime), idx) for (idx, val) in enumerate(fdates))
        _, idx2 = min((abs(val-endtime),   idx) for (idx, val) in enumerate(fdates))
        mfiles = sorted_files[idx1:idx2+1]


        ### get a subset of data
        if dataset == 'latest': # get file closest to endtime
                
                if len(mfiles) > 1:
                    mfiles = [mfiles[-1]] # need the extra brackets to the next line works

                sn_data = SNFile(mfiles[0])
                d = sn_data.read_realtime()
                d.insert(0, sn_data.datetime)
                d = pd.DataFrame([d], index=[sn_data.probe], columns=['date']+col_names).replace(-999.9,np.nan)
                
                d.drop(columns=['probe'], inplace=True)
                #print(d)
                d[col_names[1:]] = d[col_names[1:]].apply(pd.to_numeric) 
                
                d['Elevation'] = int(probe_locs[probe_id][2])
                d['Lat']       = probe_locs[probe_id][0] # overwrite with potentially 
                d['Lon']       = probe_locs[probe_id][1] # more accurate location from probe_info
                

                # data is less than 5 minutes old
                if abs(sn_data.datetime - endtime) < dt.timedelta(minutes=5):
                    met = met.append(d)  # only have to append a few times, so it's okay to use pandas
                    latestFLAG = False

                    # Write out info for Obs Table on website
#                     if html:
                        
#                         s = endtime - dt.timedelta(hours=24)
#                         _, idx1 = min((abs(val-s), idx) for (idx, val) in enumerate(fdates))
#                         _, idx2 = min((abs(val-endtime),   idx) for (idx, val) in enumerate(fdates))
#                         mfiles = sorted_files[idx1:idx2+1]

#                         data, dates = [],[] # to put data in for faster looping
#                         for f in mfiles:
#                             sn_data = SNFile(f)
#                             data.append(sn_data.read_realtime())
#                             dates.append(sn_data.datetime)

#                         met24 = pd.DataFrame(data, index=dates, columns=col_names)
#                         met24 = met24[s:endtime] # just in case 
#                         met24.drop(columns=['probe'], inplace=True)
#                         met24 = met24.astype(float)


#                         Tmax = np.round(C_to_F(np.amax(met24['T'].values)),1)     # F
#                         Tmin = np.round(C_to_F(np.amin(met24['T'].values)),1)      # F # kts
#                         WSgustmax = np.round(np.amax(met24['WSMAX'].values)* 1.94384, 1)
#                         wsindx = np.argmax(met24['WSMAX'].values) # not sure why I need this...

#                         # current vals
#                         T = C_to_F(d['T']).values[0]
#                         Td = C_to_F(calc_dewpoint(d['T'].values, d['RH'].values))[0]
#                         RH = d['RH'].values[0]
#                         WS = np.round(d['WS']* 1.94384, 1).values[0]
#                         WSgust = np.round(d['WSMAX']* 1.94384, 1).values[0]
#                         WD = get_winddir_string(d['WD'].values)
#                         batt = d['BATT'].values[0]
#                         MSLP = np.round(calc_mslp(d['T'].values,d['P'].values,d['Elevation'].values),1)[0]
#                         city = probe_locs[probe_id][4]
#                         id_name = probe_locs[probe_id][3]
#                         time = sn_data.datetime

#                         text1 = f'{city},{id_name},{probe_id},{time},{T},{Td},{RH},{WS},{WD},{WSgust:4.1f},'
#                         text2 = f'{Tmax},{Tmin},{WSgustmax:4.1f},{wsindx},{batt},{MSLP}'
#                         text = text1+text2

#                         print(text)
#                         #write_to_html(html, probe_id, endtime, d, fdates) # takes about 1.5 s per StickNet

                else: # no data
                    continue
                    
if (dataset=='latest') & (latestFLAG==False): # after all the loops, return met if latest and met isn't empty
    met.drop(columns=['YYMMDD', 'HHMM'])
    met.units = 'T(C), RH(%), P(hPa), WS(m/s), WSMAX(m/s), WD(deg)'
# elif (dataset=='latest') & (latestFLAG):
#     return met # return empty dataframe

0102A
CPU times: user 48.6 ms, sys: 20 ms, total: 68.7 ms
Wall time: 67.7 ms

In [19]:
met

,date,Lat,Lon,YYMMDD,HHMM,T,RH,P,WS,WSMAX,WD,BATT,Elevation
0102A,2017-04-30 23:59:00,34.2959,-87.5871,20170430,2359,18.8,87.5,976.6,4.9,6.7,129.6,10.7,282

In [21]:
d['T']

0102A    18.8
Name: T, dtype: float64

In [64]:
def write_to_html(html, probe_id, endtime, d, fdates):
    ''' all inputs are created in other function
    Writes to html file for website Observation Table.
    Writes out City name, 4-letter city identifer, probe id, current T, Td,
    RH, WS, WD (string format), wind gust, 24 hr max T, 24 hour min T, 24 hour Max wind gust,
    index of max wind gust (idk why this is needed), batter, MSLP.
    Units for temps are F, wind is kt, pressure is hPa, and battery is Volts. '''
    
    # 24 hour data 
    s = endtime - dt.timedelta(hours=24)
    _, idx1 = min((abs(val-s), idx) for (idx, val) in enumerate(fdates))
    _, idx2 = min((abs(val-endtime),   idx) for (idx, val) in enumerate(fdates))
    mfiles = sorted_files[idx1:idx2+1]

    data, dates = [],[] # to put data in for faster looping
    for f in mfiles:
        sn_data = SNFile(f)
        data.append(sn_data.read_realtime())
        dates.append(sn_data.datetime)
        
    met24 = pd.DataFrame(data, index=dates, columns=col_names)
    met24 = met24[s:endtime] # just in case 
    met24 = met24.astype(float)


    Tmax = np.round(C_to_F(np.amax(met24['T'])),1)     # F
    Tmin = np.round(C_to_F(np.amin(met24['T'])),1)      # F # kts
    WSgustmax = np.round(np.amax(met24['WSMAX'])* 1.94384, 1)
    wsindx = np.argmax(met24['WSMAX']) # not sure why I need this...

    # current vals
    T = C_to_F(d['T']).values[0]
    Td = C_to_F(calc_dewpoint(d['T'].values, d['RH'].values))[0]
    RH = d['RH'].values[0]
    WS = np.round(d['WS']* 1.94384, 1).values[0]
    WSgust = np.round(d['WSMAX']* 1.94384, 1).values[0]
    WD = get_winddir_string(d['WD'].values)
    batt = d['BATT'].values[0]
    MSLP = np.round(calc_mslp(d['T'].values,d['P'].values,d['Elevation'].values),1)[0]
    city = probe_locs[probe_id][4]
    id_name = probe_locs[probe_id][3]
    time = sn_data.datetime

    text1 = f'{city},{id_name},{probe_id},{time},{T},{Td},{RH},{WS},{WD},{WSgust:4.1f},'
    text2 = f'{Tmax},{Tmin},{WSgustmax:4.1f},{wsindx},{batt},{MSLP}'
    text = text1+text2

    print(text)
    #html.write(text)

In [63]:
np.argmin(met['T'])

0

In [185]:

date = '20170430'
analysis_time = dt.datetime(2017,4,30,19,8)
filedir = r'/Users/jessmcd/Documents/MyPassport_backup/VSE_Data/{}/{}/'.format(date[0:4], date)
probes= np.arange(2,18,1)

starttime=dt.datetime(2017,4,30,19,8)
endtime=dt.datetime(2017,4,30,19,18)
dataset = "latest"
#probes=[2]
   
    
plotmeteograms=False 
returndata=False
html=True
noaa=None





df = get_sticknet_data(filedir,starttime,endtime, probes=[5,4],dataset="subset",
                      plotmeteograms=False, returndata=True, html=None, noaa=None)

df

0105A

                     probe     T    RH      P   WS  WSMAX     WD  BATT
Time
2017-04-30 19:08:00  0105A  26.3  57.1  991.2  2.2    4.5  175.8  10.8
2017-04-30 19:09:00  0105A  26.4  56.8  991.3  2.3    6.0  198.9  10.8
2017-04-30 19:10:00  0105A  26.5  55.6  991.2  4.4    6.8  195.5  10.8
2017-04-30 19:11:00  0105A  26.4  55.0  991.2  4.3    6.8  191.8  10.8
2017-04-30 19:12:00  0105A  26.4  55.1  991.2  2.1    5.7  177.8  10.8
2017-04-30 19:13:00  0105A  26.5  55.9  991.1  2.2    4.0  191.1  10.8
2017-04-30 19:14:00  0105A  26.6  55.0  991.0  3.0    5.3  169.1  10.8
2017-04-30 19:15:00  0105A  26.7  56.3  991.0  2.6    4.4  192.5  10.8
2017-04-30 19:16:00  0105A  26.7  54.8  991.0  3.5    6.3  164.1  10.8
2017-04-30 19:17:00  0105A  26.7  55.2  991.0  2.8    5.7  180.6  10.8
2017-04-30 19:18:00  0105A  26.7  55.8  991.0  2.1    3.6  200.5  10.8

In [27]:
class SNFile(object):
    def __init__(self, filename):
        """ initialize a SN object based on a filename given """
        self.year = int(filename[-17:-13])
        self.month = int(filename[-13:-11])
        self.day = int(filename[-11:-9])
        self.hour = int(filename[-8:-6])
        self.minute = int(filename[-6:-4])
        self.datetime = dt.datetime(self.year,self.month,self.day,self.hour,self.minute)
        self.filename = filename
        self.probe = filename[-23:-18]

    def read_realtime(self):
        """ read the one line of the RT sticknet text file and split apart.
       """
        
        col_names = ['probe', 'Lat', 'Lon', 'YYMMDD', 'HHMM',
                    'T', 'RH', 'P', 'WS','WSMAX', 'WD', 'BATT']

        d = pd.read_csv(self.filename, header=None, names=col_names)

In [37]:



#%%timeit

sn_data = SNFile(files[0])
d = sn_data.read_realtime()#

In [57]:




#dd = pd.Series(data=d, index=col_names)

In [54]:
met.append(dd, ignore_index=True)

,probe,Lat,Lon,YYMMDD,HHMM,T,RH,P,WS,WSMAX,WD,BATT
0,0103A,34.8552,86.0018,20170430,0,25.7,57.3,955.9,4.2,5,186.5,10.7
1,0103A,34.8552,86.0018,20170430,1,25.7,57.3,955.9,4.2,7.3,190.8,10.7
2,0103A,34.8552,86.0018,20170430,2,25.7,57,955.9,5.5,7.8,188,10.7
3,0103A,34.8552,86.0018,20170430,3,25.8,57.3,955.9,4.4,5.8,176.5,10.7
4,0103A,34.8552,86.0018,20170430,4,25.8,57.3,956,3.8,4.6,182.8,10.7
...,...,...,...,...,...,...,...,...,...,...,...,...
1384,0103A,34.8552,86.0018,20170430,2318,17.3,95.4,953.9,5,6.1,178.8,10.7
1385,0103A,34.8552,86.0018,20170430,2319,17.3,95.4,953.9,5.7,7.7,176.4,10.7
1386,0103A,34.8552,86.0018,20170430,2320,17.3,95.3,953.9,5.7,7.5,169.8,10.7
1387,0103A,34.8552,86.0018,20170430,2321,17.3,95.3,954,5.1,7.2,178,10.7
1388,0103A,34.855170,86.001761,20170430,1839,24.3,63.7,954.9,6.5,9.2,175.9,10.7

In [58]:
dd

,probe,Lat,Lon,YYMMDD,HHMM,T,RH,P,WS,WSMAX,WD,BATT
2017-04-30 18:39:00,0103A,34.855170,86.001761,20170430,1839,24.3,63.7,954.9,6.5,9.2,175.9,10.7